<?php $postsCollection = $this->getWidgetFormData();
if (!$postsCollection):?>
    <div class="note-msg"><?php echo Mage::helper('flexibleblog')->__('There are no posts matching the selection.'); ?></div>
<?php else:
    //To retive latest post
    foreach($postsCollection as $post):?>
        <div class="blog post-content">
            <div class="page-title post-title">
                <h2><a href="<?php echo $this->getPostUrl( $post->getPostUrlKey()); ?>"><?php echo $post->getPostTitle(); ?></a></h2>
            </div>
            <div class="post-metadata">
                <div class="post-date"><?php echo Mage::helper('core')->formatDate($post->getPostPublishDate(), 'medium', false); ?></div>
                <div class="post-author"><?php echo $this->__('By '); ?><a href="<?php echo $this->getAuthorUrl($post->getPostAuthor()); ?>"><?php echo $this->getAuthorName($post->getPostAuthor()); ?></a></div>
                <?php if(Mage::helper('flexibleblog')->enableComment() != 0 ): ?>
                    <div class="post-comment">
                        <a href="<?php echo $this->getPostUrlById($post->getPostId()); ?>#post-comments">
                            <?php echo $this->getComments($post->getPostId());?>
                        </a>
                    </div>
                <?php endif; ?>
            </div>

            <?php //To retrive post feature image
            $postImage = $this->getLatestPostThumb($post->getPostId());
            if($postImage): ?>
                <div class="post-image">
                    <figure><?php echo $this->getLatestPostThumb($post->getPostId()); ?></figure>
                </div>
            <?php endif; ?>

            <div class="post-summary">
                <?php echo $this->getPostExcerpt($post->getPostId()); ?>
                <div class="read-more"><a href="<?php echo $this->getPostUrl($post->getPostUrlKey()); ?>" class="button"><?php echo $this->__('Read More'); ?></a></div>
            </div>

            <div class="post-info">
                <?php echo $this->__('Posted in: '); ?>
                <ul class="post-categories">
                    <?php echo $this->getPostCategoryList($post->getPostCategories()); //To show post categories ?>
                </ul>
                <?php //To retrive post tags list
                $tagList = $this->getPostTagList($post->getPostTags());
                if($tagList): ?>
                    <?php echo $this->__('Tagged: '); ?>
                    <ul class="post-tags">
                        <?php echo $tagList; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach;
    //Load disqus script if disqus comments enable from blog configration settings
    echo $this->getDisqusScript();
endif; ?>