<?php
/** @var TM_Catalog_Block_Combo $this */
$collection = $this->_getProductCollection();
/** @var Mage_Catalog_Helper_Output $_helper */
$_helper = $this->helper('catalog/output');
?>
<div class="pro-container text-center">
    <div class="pro-wrp product-list">
        <div class="row">
            <?php
            if ($collection->count()) {
                /** @var Mage_Catalog_Model_Product $_product */
                foreach ($collection as $_product) {
                    ?>
                    <div class="col-sm-4 col-md-3 col-xs-12 ">
                        <div class="item">
                            <div class="pro-item product-primary ">
                                <div class="thumbnail">
                                    <a href="<?php echo $_product->getProductUrl() ?>">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240); ?>"
                                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                        <div class="caption text-center">
                                            <h3 class="text-xlg pro-tit"
                                                title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h3>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <div class="product-secondary ">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            </div>
                            <div class="product-secondary buttons ">
                                <?php if (!$_product->canConfigure() && $_product->isSaleable()): ?>
                                    <p class="action">
                                        <button type="button"
                                                title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>"
                                                class="button btn-cart"
                                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    </p>
                                <?php elseif ($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                    <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>"
                                                         class="button"
                                                         href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                                    </p>
                                <?php else: ?>
                                    <p class="action availability out-of-stock">
                                        <span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                               class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php
                }
            } else {
                echo $this->__('There are no products matching the selection.');
            }
            ?>
        </div>
        <?php if ($collection->count()) { ?>
            <div class="text-center">
                <a href="<?php echo $this->getCurrentCategoryUrl() ?>"
                   class="button"><?php echo $this->__('Shop All Now') ?></a>
            </div>
        <?php } ?>
    </div>
</div>

