<?php
/**
 * Home Slider
 */
?>

<div class="home-banner">
    <div class="row">
        <div class="col-md-8 col-xs-12">
            <div class="home-banner-slider">
                <div><img src="<?php echo $this->getSkinUrl('images/upload/banner1.jpg') ?>" alt="" /></div>
                <div><img src="<?php echo $this->getSkinUrl('images/upload/banner2.jpg') ?>" alt="" /></div>
                <div><img src="<?php echo $this->getSkinUrl('images/upload/banner3.jpg') ?>" alt="" /></div>
            </div>
        </div>
        <div class="col-md-4 hidden-xs">
            <div class="static-banner"><img src="<?php echo $this->getSkinUrl('images/upload/banner4.jpg') ?>" alt="" /></div>
        </div>
    </div>
</div>

