<?php $post_url = $this->getPostUrlKey(); 
$postId = $this->getRequest()->getParam('id');
$disqusId= $this->getDisqusUsername();
if($disqusId)
{?>
    <div class="comment-box">
        <h2><?php echo Mage::helper('core')->__('Leave a Comment'); ?></h2>
        <div class="comment">
            <div id="disqus_thread"></div>
            <script>
                /**
                *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                var disqus_config = function () {
                    this.page.url = '<?php echo $this->getPostUrlById( $postId ); ?>';  // Replace PAGE_URL with your page's canonical URL variable
                    this.page.identifier = '<?php echo $this->getPostUrlKeyById( $postId ); ?>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                };

                (function() { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = '//<?php echo $disqusId;?>.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            <?php echo $this->getDisqusScript(); ?>
        </div>
    </div>
<?php 
}
else
{?>
    <div class="flexible-comment-error"><p><?php echo $this->__('Something is wrong !'); ?></p></div>
<?php }